"""empty message

Revision ID: 0d06632b3a1a
Revises: dfbaef247443
Create Date: 2020-12-07 20:39:49.019847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d06632b3a1a'
down_revision = 'dfbaef247443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CalibrationModel', sa.Column('highValue', sa.Float(), nullable=True))
    op.add_column('CalibrationModel', sa.Column('hvMin', sa.Float(), nullable=True))
    op.add_column('CalibrationModel', sa.Column('hvPlus', sa.Float(), nullable=True))
    op.add_column('CalibrationModel', sa.Column('lowValue', sa.Float(), nullable=True))
    op.add_column('CalibrationModel', sa.Column('lvMin', sa.Float(), nullable=True))
    op.add_column('CalibrationModel', sa.Column('lvPlus', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CalibrationModel', 'lvPlus')
    op.drop_column('CalibrationModel', 'lvMin')
    op.drop_column('CalibrationModel', 'lowValue')
    op.drop_column('CalibrationModel', 'hvPlus')
    op.drop_column('CalibrationModel', 'hvMin')
    op.drop_column('CalibrationModel', 'highValue')
    # ### end Alembic commands ###
