"""empty message

Revision ID: 0e73da73eb94
Revises: 9e743c21c764
Create Date: 2020-12-18 11:21:44.034388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e73da73eb94'
down_revision = '9e743c21c764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CalibrationModel', sa.Column('brand', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CalibrationModel', 'brand')
    # ### end Alembic commands ###
