"""empty message

Revision ID: 9ae4a7b1f57a
Revises: d64b2f2b79b4
Create Date: 2021-01-06 13:39:35.213308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae4a7b1f57a'
down_revision = 'd64b2f2b79b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memoryModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memoryModel')
    # ### end Alembic commands ###
