"""empty message

Revision ID: 9e743c21c764
Revises: 6271defafd41
Create Date: 2020-12-18 11:16:12.286678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e743c21c764'
down_revision = '6271defafd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CalibrationModel', sa.Column('ref', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CalibrationModel', 'ref')
    # ### end Alembic commands ###
