"""empty message

Revision ID: a3bf97df549e
Revises: 9ae4a7b1f57a
Create Date: 2021-01-06 13:50:23.041129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bf97df549e'
down_revision = '9ae4a7b1f57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('memoryModel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memoryModel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('memory')
    # ### end Alembic commands ###
