"""empty message

Revision ID: e86c956417dc
Revises: 
Create Date: 2020-12-08 11:32:49.828660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86c956417dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CalibrationModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('type_a', sa.Integer(), nullable=True),
    sa.Column('a_highValue', sa.Float(), nullable=True),
    sa.Column('a_hvPlus', sa.Float(), nullable=True),
    sa.Column('a_hvMin', sa.Float(), nullable=True),
    sa.Column('a_lowValue', sa.Float(), nullable=True),
    sa.Column('a_lvPlus', sa.Float(), nullable=True),
    sa.Column('a_lvMin', sa.Float(), nullable=True),
    sa.Column('type_b', sa.Integer(), nullable=True),
    sa.Column('b_highValue', sa.Float(), nullable=True),
    sa.Column('b_hvPlus', sa.Float(), nullable=True),
    sa.Column('b_hvMin', sa.Float(), nullable=True),
    sa.Column('b_lowValue', sa.Float(), nullable=True),
    sa.Column('b_lvPlus', sa.Float(), nullable=True),
    sa.Column('b_lvMin', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CalibrationModel')
    # ### end Alembic commands ###
